作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [12]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
inv_arr1 = np.linalg.inv(array1)
print('inverse array1:\n',inv_arr1)
mularr1_inv = np.matmul(array1, inv_arr1)
print(mularr1_inv)
ide_arr = np.identity(2)
print(ide_arr)
print(np.equal(mularr1_inv, ide_arr))

inverse array1:
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[ True  True]
 [ True  True]]


In [21]:
#2. 運用上列array計算特徵值、特徵向量?
eigva_arr1, eigve_arr1 = np.linalg.eig(array1)
print('array1 eigen value:\n',eigva_arr1,'\narray1 eigen vector:\n', eigve_arr1)

array1 eigen value:
 [13.  2.] 
array1 eigen vector:
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [23]:
#3. 運用上列array計算SVD?
u_arr1, s_arr1, vh_arr1 = np.linalg.svd(array1)
print('array1 SVD(u):\n', u_arr1)
print('array1 SVD(s):\n', s_arr1)
print('array1 SVD(vh):\n', vh_arr1)

array1 SVD(u):
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
array1 SVD(s):
 [13.94721714  1.86417116]
array1 SVD(vh):
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
